apiVersion: v1
kind: Service
metadata:
 name: fleetman-webapp-service
spec:
 # this defines which pod is going to be represented by this service
 selector:
  app: webapp
 ports:
 - name: http
   port: 80
   nodePort: 30080
 type: NodePort

---

apiVersion: v1
kind: Service
metadata:
 name: fleetman-queue-service
spec:
 selector:
  app: queue
 ports:
 - name: http
   port: 8161
   nodePort: 30010
 type: NodePort